layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: http://instagram.com/samird
  # keybase: your_username
  # linkedin: samirdurrani
  # mastodon: your_username
  # medium: samirrr9
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: http://twitter.com/samird
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Surf
    web_url: https://magicseaweed.com/developer/forecast-api
    image_url: https://cdn2.iconfinder.com/data/icons/hobby-butterscotch-vol-3/512/Surfing-512.png

  - name: Python
    web_url: https://www.python.org/
    image_url: http://icons.iconarchive.com/icons/cornmanthe3rd/plex/256/Other-python-icon.png

  - name: Pride
    web_url: https://donate.lalgbtcenter.org/secure/help-build-world-where-lgbt-people-thrive
    image_url: https://image.flaticon.com/icons/svg/2620/2620829.svg

  - name: Politics
    web_url: https://www.dataforprogress.org/
    image_url: https://www.jing.fm/clipimg/full/195-1957575_capitol-building-icon-transparent.png

  - name: Gender Equity
    #web_url: https://genderstats.un.org/
    image_url: https://www.lbcc.edu/sites/main/files/imagecache/lightbox/main-images/preferred-name-gender-tile.jpg

  - name: Natty Wine
    web_url: https://www.bonappetit.com/story/is-natural-wine-better-for-the-planet
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRhuf-PGfG_YFzofeAmuH-3SMd7qmiV-drwPT51AdM7SiJ_RCOn
