layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: http://instagram.com/samird
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  medium: https://medium.com/@samird
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: http://twitter.com/samird
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Competition & Antitrust
    web_url: https://comparativecompetitionlaw.org
    image_url: https://cdn1.iconfinder.com/data/icons/business-and-marketing-8/174/BUSINESS_AND_MARKETING_Black-24-512.png

  - name: AI Ethics

  - name: Politics
    web_url: https://www.dataforprogress.org/
    image_url: https://www.jing.fm/clipimg/full/195-1957575_capitol-building-icon-transparent.png

  - name: Gender Equity
    web_url: https://genderstats.un.org/
    image_url: https://www.lbcc.edu/sites/main/files/imagecache/lightbox/main-images/preferred-name-gender-tile.jpg

  - name: Surf
    web_url: https://magicseaweed.com/developer/forecast-api
    image_url: https://cdn2.iconfinder.com/data/icons/hobby-butterscotch-vol-3/512/Surfing-512.png

  - name: Natty Wine
    web_url: https://www.bonappetit.com/story/is-natural-wine-better-for-the-planet
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRhuf-PGfG_YFzofeAmuH-3SMd7qmiV-drwPT51AdM7SiJ_RCOn
